app:
  client-url: http://localhost:8080/clientes

spring:
  application:
    name: account
  docker:
    compose:
      enabled: true
      file: compose.yaml
      lifecycle-management: start_only
  flyway:
    locations: classpath:db/migration/{vendor}
    enabled: true
  jpa:
    hibernate:
      ddl-auto: validate
    show_sql: true

server:
  error:
    include-stacktrace: never
    whitelabel:
      enabled: false
  port: 8081

logging:
  level:
    root: info
    web: DEBUG
    org:
      springframework:
        data: DEBUG