version: '3.8'

services:
  postgres_db:
    image: 'postgres:16-alpine'
    ports:
      - '5433:5432'
    environment:
      - POSTGRES_USER=practice_postgres
      - POSTGRES_PASSWORD=practice_postgres
      - POSTGRES_DB=practice_account
