spring:
  profiles:
    active: "prod"
  application:
    name: client
  docker:
    compose:
      enabled: true
      file: compose.yaml
      lifecycle-management: start_only
  flyway:
    locations: classpath:db/migration/{vendor}
    enabled: true
  jpa:
    hibernate:
      ddl-auto: validate
    show_sql: true
  datasource:
    username: ${DB_USER:practice_postgres}
    password: ${DB_PASSWORD:practice_postgres}
    url: jdbc:postgresql://${DB_URL:localhost:5432/practice_client}

server:
  error:
    include-stacktrace: never
    whitelabel:
      enabled: false
  port: 8080

logging:
  level:
    root: info
    web: DEBUG
    org:
      springframework:
        data: DEBUG